version: '3'

services:
  reverse-proxy:
    restart: always
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  image-service:
    deploy:
      replicas: 2
    restart: always
    build:
      context: ./image-service
    image: image-service:dev
    volumes:
      - ./image-service/src:/usr/src/main/src
    labels:
      traefik.docker.network: traefik
      traefik.port: 5000
      traefik.frontend.rule: Host:image.docker.localhost
    environment:
      - FLASK_ENV=production
      - PORT=5000
