apiVersion: v1
data:
  traefik.toml: |
    logLevel = "INFO"
    defaultEntryPoints = ["http", "https"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/tls/dot.minikube/tls.crt"
          KeyFile = "/tls/dot.minikube/tls.key"

    [api]

    [web]
    address = ":8080"

    [kubernetes]
    namespaces = ["default", "kube-system"]
kind: ConfigMap
metadata:
  name: treafik-toml-configmap
  namespace: kube-system
